name: Check for Changes

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in a specific folder
        id: check_changes
        run: |
          git fetch
          CHANGED_FILES=$(git diff --name-only origin/main secret-santa-app)
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in the specified folder: $CHANGED_FILES"
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in the specified folder. Exiting."
            echo "changes=false" >> $GITHUB_ENV
            exit 0
          fi

      - name: Do something if changes present
        if: env.changes == 'true'
        run: |
          # Добавьте сюда действия, которые нужно выполнить в случае наличия изменений в указанной папке
          echo "There are changes in the specified folder, performing necessary actions."
