name: Check for Server Changes

on:
  push:
    branches:
      - main

jobs:
  check_server_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the list of changed files in the server folder
        id: check_server_changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- secret-santa-app/)
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in the server folder: $CHANGED_FILES"
            echo "::set-output name=server_changes::true"
          else
            echo "No changes detected in the server folder. Exiting."
            echo "::set-output name=server_changes::false"
            exit 0
          fi

      - name: Do something if server changes present
        if: steps.check_server_changes.outputs.server_changes == 'true'
        run: |
          # Добавьте сюда действия, которые нужно выполнить в случае наличия изменений в папке server
          echo "There are changes in the server folder, performing necessary actions."
