name: Show Cache Contents

on: workflow_dispatch

jobs:
  show_cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Display Cache Contents
      run: |
        # Проверяем наличие кэша для указанной папки
        if [[ -d "$HOME/.cache/secret-santa-app" ]]; then
          echo "Кэш для папки secret-santa-app найден:"
          # Выводим содержимое кэша
          ls -la "$HOME/.cache/secret-santa-app"
        else
          echo "Кэш для папки secret-santa-app не найден."
        fi
