name: ci

on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello Github Actions!
     