name: ci

on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: el.reeeey@gmail.com
          password: ACO07144DJDFY10
     