name: ci

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get current tag
        id: get_tag
        run: echo "::set-output name=TAG::$(curl -sS "https://registry.hub.docker.com/v2/repositories/isacoolvov/secret-santa-app/tags/latest" | jq -r '.name')"

      - name: Increment tag
        id: increment_tag
        run: echo "::set-output name=NEW_TAG::$(echo ${{ steps.get_tag.outputs.TAG }} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: secret-santa-app
          push: true
          tags: isacoolvov/secret-santa-app:${{ steps.increment_tag.outputs.NEW_TAG }}
     
